export enum ChatEventEnum {
  CONNECTED_EVENT = "connect",
  STUDENT_REQUEST_CHAT = "student_request_chat",
  NEW_CHAT_REQUEST = "new_chat_request",
  VOLUNTEER_ACCEPT_REQUEST = "volunteer_accept_request",
  START_CHAT = "start_chat",
  SEND_MESSAGE = "send_message",
  RECEIVE_MESSAGE = "receive_message",
  ERROR_EVENT = "error_event",
  JOIN_ROOM = "join_room",
  GET_MESSAGES = "get_messages",
  LEAVE_ROOM = "leave_room",
  GET_REQUESTS = "get_requests",
  CANCEL_REQUEST = "cancel_request",
  REQUEST_ACCEPTED = "request_accepted",
  GET_ACTIVE_ROOM = "get_active_room",
}
